#!/bin/bash

# Parse command-line arguments
for arg in "$@"; do
    case "$arg" in
        version=*) GATE_VERSION="${arg#*=}" ;;
        lite=*) GATE_LITE="${arg#*=}" ;;
        *) ;;
    esac
done

echo -e "\e[1;32mDebug: Version ${GATE_VERSION} is selected. Gate Lite is ${GATE_LITE}\e[0m"

# Check if GATE_VERSION is provided and available on GitHub
if [ -z "${GATE_VERSION}" ] || [ "${GATE_VERSION}" == "latest" ]; then
    GATE_VERSION=$(curl -s https://api.github.com/repos/minekube/gate/releases/latest | jq -r .tag_name)
    echo -e "\e[1;36mGate Version selected is ${GATE_VERSION}\e[0m"
else
    # Attempt to download the provided version
    DOWNLOAD_URL="https://github.com/minekube/gate/releases/download/${GATE_VERSION}/gate_${GATE_VERSION#v}_linux_amd64"
    if wget -O /dev/null -q --spider "${DOWNLOAD_URL}"; then
        echo -e "\e[1;32mDebug: Version ${GATE_VERSION} is available.\e[0m"
    else
        echo -e "\e[1;31mProvided GATE_VERSION (${GATE_VERSION}) is not available. Defaulting to latest.\e[0m"
        GATE_VERSION=$(curl -s https://api.github.com/repos/minekube/gate/releases/latest | jq -r .tag_name)
        echo -e "\e[1;36mGate Version selected is ${GATE_VERSION}\e[0m"
    fi
fi


chmod +x "gate"
